DROP TABLE CART;

CREATE TABLE CART(
    CARTNUM NUMBER(8) PRIMARY KEY,
    IDX_FK  NUMBER(8) REFERENCES MEMBER (IDX) ON DELETE CASCADE,
    PNU_FK  NUMBER(8) REFERENCES MEMBER (PNUM) ON DELETE CASCADE,
    OQTY NUMBER(8) NOT NULL,
    INDATE DATE DEFAULT SYSDATE,
    CONSTRAINT CART_OQTY_CK CHECK (OQTY > 0 AND OQTY < 51)
    );
    
    DROP SEQUENCE CART_SEQ;
    
    CREATE SEQUENCE CART_SEQ NOCACHE;